### ISSUE TITLE
Not all files have "gn" as part of name file

### ISSUE THREAD

**Issue by anacarolinafxavier19** [hllauca/RClimChange#2]
Hi, this is a great package. The name file for some models does not include "_gn_."
Because your source code in line 162 sets: "paste0(var,' day ',mod,' ',per,' ',run,' gn_', yr,'.nc')" models like KIOST-ESM and KACE have download errors.

**Comment by anacarolinafxavier19** [comment]
Models with native grid (gn) as grid_label: ('TaiESM1','NorESM2-MM','NorESM2-LM','NESM3','MRI-ESM2-0','MPI-ESM1-2-LR','MPI-ESM1-2-HR','MIROC6','IITM-ESM','CanESM5','CMCC-CM2-SR5','CMCC-ESM2','CMCC-CM2-SR5','BCC-CSM2-MR','ACCESS-ESM1-5',
'ACCESS-CM2','UKESM1-0-LL','MIROC-ES2L','GISS-E2-1-G','HadGEM3-GC31-MM','HadGEM3-GC31-LL','FGOALS-g3',
'CESM2-WACCM', 'CESM2'

**Comment by hllauca** [comment]
I recently add some conditionals to solve this issue. Please check!
