### ISSUE TITLE
When replication your example I have the following error "Error in nc_open(tempfile)"  

### ISSUE THREAD

**Issue by NoeNava-USDA** [hllauca/RClimChange#3]
When replicating your example in the documentation, I encounter the following error. I tested changing the settings, but that does not seem to work

```
Error in nc_open(tempfile) : 
  Error in nc_open trying to open file data/test/pr/historical/BCC-CSM2-MR/temp_file.nc (return_on_error= FALSE )
```

This is my code, which appears also in your documentation:

```
devtools::install_github("hllauca/RClimChange", dependencies = TRUE)
library(RClimChange)

gcm_download_data(location = 'data/test',
                  model    = 'BCC-CSM2-MR',
                  scenario = 'historical',
                  variable = 'pr',
                  years    = '1990',
                  roi      = c(-86, -66, -20, 2),
                  method   = 'curl')
```

**Comment by hllauca** [comment]
It seems that the NEX-GDDP-CMIP6 server is unavailable now and that doesn't depend on this R package. Please try again when the FTP server is working (https://ds.nccs.nasa.gov/thredds/catalog/AMES/NEX/GDDP-CMIP6/catalog.html)

![image](https://user-images.githubusercontent.com/9383944/161847557-2c357882-673a-43d5-95a1-a14ca8d07334.png)
